language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer install --prefer-dist --dev
    - phpenv rehash

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
